// @generated by protoc-gen-es v2.8.0 with parameter "target=ts"
// @generated from file ledger/v1/event.proto (package ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ledger/v1/event.proto.
 */
export const file_ledger_v1_event: GenFile = /*@__PURE__*/
  fileDesc("ChVsZWRnZXIvdjEvZXZlbnQucHJvdG8SCWxlZGdlci52MSJdCgtMZWRnZXJFbnRyeRIKCgJpZBgBIAEoCRISCgpldmVudF90eXBlGAIgASgJEg4KBnJlZl9pZBgDIAEoCRIPCgdwYXlsb2FkGAQgASgMEg0KBXRzX21zGAUgASgDQkxaSmdpdGh1Yi5jb20vZG91Z2xhc2JyaXQwL3Nwb3J0LWV4Y2hhbmdlL2NvbnRyYWN0cy9nZW4vZ28vbGVkZ2VyL3YxO2xlZGdlcnYxYgZwcm90bzM");

/**
 * @generated from message ledger.v1.LedgerEntry
 */
export type LedgerEntry = Message<"ledger.v1.LedgerEntry"> & {
  /**
   * uuid
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * e.g. "ORDER_PLACED"
   *
   * @generated from field: string event_type = 2;
   */
  eventType: string;

  /**
   * correlation id
   *
   * @generated from field: string ref_id = 3;
   */
  refId: string;

  /**
   * serialized sub-message (Json/Proto)
   *
   * @generated from field: bytes payload = 4;
   */
  payload: Uint8Array;

  /**
   * epoch ms
   *
   * @generated from field: int64 ts_ms = 5;
   */
  tsMs: bigint;
};

/**
 * Describes the message ledger.v1.LedgerEntry.
 * Use `create(LedgerEntrySchema)` to create a new message.
 */
export const LedgerEntrySchema: GenMessage<LedgerEntry> = /*@__PURE__*/
  messageDesc(file_ledger_v1_event, 0);

