//
//syntax = "proto3";
//package engine.v1;
//
//import "google/protobuf/timestamp.proto";
//
//message QuoteRequest { string symbol = 1; }
//
//message QuoteResponse {
//double bid = 1;
//double ask = 2;
//google.protobuf.Timestamp ts = 3;
//}
//
//service Quotes {
//rpc GetQuote(QuoteRequest) returns (QuoteResponse);
//}

// @generated by protoc-gen-es v2.8.0 with parameter "target=ts"
// @generated from file engine/v1/quote.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/quote.proto.
 */
export const file_engine_v1_quote: GenFile = /*@__PURE__*/
  fileDesc("ChVlbmdpbmUvdjEvcXVvdGUucHJvdG8SCWVuZ2luZS52MSJBCgxRdW90ZVJlcXVlc3QSEQoJcGxheWVyX2lkGAEgASgJEg4KBm1hcmtldBgCIAEoCRIOCgZyZXFfaWQYAyABKAkiaAoNUXVvdGVSZXNwb25zZRIRCglwbGF5ZXJfaWQYASABKAkSCwoDYmlkGAIgASgBEgsKA2FzaxgDIAEoARILCgNtaWQYBCABKAESDQoFdHNfbXMYBSABKAMSDgoGcmVxX2lkGAYgASgJQnEKI2NvbS55b3Vyb3JnLnNwb3J0ZXhjaGFuZ2UuZW5naW5lLnYxWkpnaXRodWIuY29tL2RvdWdsYXNicml0MC9zcG9ydC1leGNoYW5nZS9jb250cmFjdHMvZ2VuL2dvL2VuZ2luZS92MTtlbmdpbmV2MWIGcHJvdG8z");

/**
 * @generated from message engine.v1.QuoteRequest
 */
export type QuoteRequest = Message<"engine.v1.QuoteRequest"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  /**
   * e.g., "EPL"
   *
   * @generated from field: string market = 2;
   */
  market: string;

  /**
   * correlation id
   *
   * @generated from field: string req_id = 3;
   */
  reqId: string;
};

/**
 * Describes the message engine.v1.QuoteRequest.
 * Use `create(QuoteRequestSchema)` to create a new message.
 */
export const QuoteRequestSchema: GenMessage<QuoteRequest> = /*@__PURE__*/
  messageDesc(file_engine_v1_quote, 0);

/**
 * @generated from message engine.v1.QuoteResponse
 */
export type QuoteResponse = Message<"engine.v1.QuoteResponse"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  /**
   * @generated from field: double bid = 2;
   */
  bid: number;

  /**
   * @generated from field: double ask = 3;
   */
  ask: number;

  /**
   * @generated from field: double mid = 4;
   */
  mid: number;

  /**
   * @generated from field: int64 ts_ms = 5;
   */
  tsMs: bigint;

  /**
   * mirrors request
   *
   * @generated from field: string req_id = 6;
   */
  reqId: string;
};

/**
 * Describes the message engine.v1.QuoteResponse.
 * Use `create(QuoteResponseSchema)` to create a new message.
 */
export const QuoteResponseSchema: GenMessage<QuoteResponse> = /*@__PURE__*/
  messageDesc(file_engine_v1_quote, 1);

